### PR TITLE
Training Presentations and Other Supporting Materials

### PR DESCRIPTION
**Pull request by bernars-usa**
Addresses most of https://github.com/usds/OPM_pilot/issues/446 (all except RR training). Specifically, this adds the Day 1 and Day 2 job analysis workshop PPTs and the interview training PPT to the toolkits for those phases.

This also turns the Markdown versions of the sample competencies, proficiencies, and interview questions into a downloadable Word doc that can be printed and distributed at the job analysis workshop, as @stephaniefaith asked.

### CODE REVIEW

**Comment by bernars-usa** [comment]
@humancompanion-usds - I can't see what's failing the build here, can you help?

**Comment by humancompanion-usds** [comment]
Yeah, it's failing because of your change in pull request #38  where you added the email svg:

> jekyll 3.8.5 | Error:  Could not locate the included file 'svg/file-email.svg' in any of ["/work/site_repo/_includes", "/usr/local/rvm/gems/ruby-2.6.3/gems/jekyll-theme-primer-0.5.3/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode.

Let me pull down that branch and add the svg file. That should fix it.

**Comment by bernars-usa** [comment]
> it's failing because of your change in pull request #38

Ah, I didn't realize it would fail every PR until the one error was fixed in another branch. 😕

**Comment by bernars-usa** [comment]
> Do we need to add these to the queue for OPM Policy?

I don't believe so, as we're not seeking clearance for the website right now.

> Just wondering if we need to keep a running list of diffs. If that is necessary, perhaps the change log would suffice? Perhaps make an update there next?

Yes, I'm going to make a single change log update for this PR and #38. 👍

**Pull request merged**
